### ISSUE TITLE
goat record create "error: unrecognized lexicon"

### ISSUE THREAD

**Issue by tom-sherman** [bluesky-social/indigo#775] opened 2024-10-06 10:29 UTC
Version:  v0.0.0-20241004163428-2e5d3d7efe62

```
goat record create record.json
```

record.json:

```json
{
  "collection": "app.bsky.feed.post",
  "repo": "did:plc:2xau7wbgdq4phuou2ypwuen7",
  "record": {
    "text": "test",
    "langs": ["en"],
    "createdAt": "2024-01-01T10:21:30.965Z",
    "$type": "app.bsky.feed.post"
  }
}
```

Expected: record to be created

Actual:

```
error: unrecognized lexicon type: ""
```

**Comment by bnewbold** [comment] 2024-10-07 00:41
I think you want to have the record JSON be just the record itself, without the "wrapper" with collection and repo. The relevant repo is detected by auth; the collection by the `$type` in the record itself; and an rkey can be provided via argument.

**Comment by bnewbold** [comment] 2024-11-07 21:35
This may actually have been caused by a thing I just fixed in https://github.com/bluesky-social/indigo/issues/784

**Comment by bnewbold** [comment] 2024-11-07 21:35
Closing assuming that fixes things (I was able to create a new unknown lexicon record just now), please re-open if not.

**Closed by bnewbold** 2024-11-07 21:35 UTC
